### ISSUE TITLE
Development Cycle

### ISSUE THREAD

**Issue by Einstein42** [UniversalDevicesInc/Polyglot#12]
How are you all envisioning we do this? Fork and pull or branch? I've been doing my usual fork and pull, but it looks like Jimbo is using the branch. Doesn't matter to me, just figured we should all be on the same page. 

-James

**Comment by jimboca** [comment]
Yes, I agree.  I assumed that Michel wanted us to work inside by creating branches when he added me to the organization.  I think all this is new for UDI and he will figure out how we should work and let us know.

**Comment by Einstein42** [comment]
Works for me!
