### ISSUE TITLE
sandbox should be available to node servers

### ISSUE THREAD

**Issue by jimboca** [UniversalDevicesInc/Polyglot#21]
The NodeServer creates a 'sandbox' which is a directory in the config dir for that specific SimpleNodeServer instance.  This should also be available to the SimpleNodeServer to store logs.

I have implemented the same way @Einstein42 did for isyver for #8.

This is functional and tested.

```
DEBUG    [03-24-2016 20:12:47] polyglot.nodeserver_manager: ihcam STDIN: {"sandbox": {"sandbox": "/home/pi/development/Polyglot/config/camera"}}
```

Accessible by: self.poly.sandbox from SimpleNodeServer(NodeServer)

If nobody has an issue with it, then I will commit.

**Comment by Einstein42** [comment]
Nice. Go ahead. I hadn't gotten around to it yet, I've been busy this week.
Thanks for tackling that.

**Comment by jimboca** [comment]
No worries, after seeing where sandbox was defined, then seeing how you implemented isyver, it made it easy.  I've tested it a bunch so I will commit.

**Comment by jimboca** [comment]
Changes committed to development branch and working.
