### ISSUE TITLE
Merged in a systemd init script

### ISSUE THREAD

**Issue by Einstein42** [UniversalDevicesInc/Polyglot#3]
Still need to add it to Make install but the init script is there now.

**Comment by jimboca** [comment]
Thanks for adding that :)  But, does: /usr/bin/python -m polyglot -v
work for you?  I could only get that working with python3 ?

**Comment by Einstein42** [comment]
Yea it works for me.

**Comment by Einstein42** [comment]
Jimbo, what error are you getting when running with python 2.7? I had a challenge getting some of the dependencies right, but once I did everything seems to be fine.

**Comment by jimboca** [comment]
When I originally cloned and tried running it would not work, after seeing
your post I tried again and it worked fine. Thanks!
