### ISSUE TITLE
Add RESTCALL API to Polyglot

### ISSUE THREAD

**Issue by mjwesterhof** [UniversalDevicesInc/Polyglot#40]
Add the ability for a node server to perform a simple REST API and fetch the response via Polyglot.

A prototype of this feature has proven to be very useful in testing ISY/Polyglot communications.  It may prove to be useful for Node Servers in general (in which case it would need documentation and perhaps an example of how to use it).

The code that fetches the ISY version already performs a REST api call; this work simply generalizes that code and exposes it in nodeserver_manager.py right now.

(Barring objection from the team, I'll clean up this code and commit an initial version of this later today.)

**Comment by jimboca** [comment]
I'd like to see what you have. I proposed this on the forum and was shot
down. Although I needed one with no password access so I added a simple
interface just for foscam cameras to send Motion events inside my node
server.

**Comment by mkohanim** [comment]
Excellent addition!!! Thank you.

With kind regards,

---

  Michel Kohanim
  CEO

**Comment by mjwesterhof** [comment]
Committed the changes to the development branch.
Note that the REST calls referred to in this issue are from a node server _to_ the ISY - it's very limited in scope.  There are a number of security considerations involved in what we want to let the polyglot server do on behalf of a node server; we should tackle the issue of _incoming_ REST API calls to a node server separately.

**Comment by mjwesterhof** [comment]
Merging this issue with #42 ; a good solution for that one will include any work remaining on this issue as well as doing the necessary testing.
