### ISSUE TITLE
Node class should check address length

### ISSUE THREAD

**Issue by jimboca** [UniversalDevicesInc/Polyglot#5]
The maximum node address length is 19, so after the n000_ prefix, a node server node address length can only be 14.  So I think we should check this when a node is created since we don't see any meaningful error message from the ISY, besides just that the node could not be created.

**Comment by Einstein42** [comment]
So what do you recommend here, should we truncate the node name to 14 characters or return a catch value to fail?

**Comment by jimboca** [comment]
Not sure, I was thinking at least print an error to the log file and return
false.

**Comment by Einstein42** [comment]
I'm having a hell of a time finding where the profile_number + address is even generated. I thought I found it the other day, but can't seem to find it tonight.

**Comment by Einstein42** [comment]
There is currently no error handling to return null on this, and it fails anyway, so I just added an error message to the log so at least the user knows. I don't know that more is necessary. Thoughts?

**Comment by jimboca** [comment]
Yes that will help. Not sure if it should throw an exception.
