### ISSUE TITLE
Passing int instead of float to ISY

### ISSUE THREAD

**Issue by Einstein42** [UniversalDevicesInc/Polyglot#51]
Received command:
kwargs: {'cmd': u'OutBack_Load_Grid_Transfer_Threshold', 'value': 15.0, 'uom': 30}

Set command
self.set_driver('OutBack_Load_Grid_Transfer_Threshold', 15.0)

Passed to ISY
GET /ns/MXVlt/nodes/n004_ax1430f0100397/cmd/OutBack_Load_Grid_Transfer_Threshold/15/30

**Comment by jimboca** [comment]
Does this happen even if you pass 15.1 ?  I pass floats in my polyglot with no issue?  Or is it because of the uom?

**Comment by Einstein42** [comment]
No. Any float works fine. Just anything .0

I have opened a ticket with ISY as well as this could be their issue.

**Comment by jimboca** [comment]
Ok, sounds good.

**Comment by Einstein42** [comment]
This is fixed in 5.0.4+ of ISY, closing as non-polyglot issue.
