### ISSUE TITLE
Hue Node Server pinging of Hue hub should be configurable

### ISSUE THREAD

**Issue by mjwesterhof** [UniversalDevicesInc/Polyglot#9]
Currently the Hue node server contacts the Hue hub once per second.  This is probably appropriate for most functional networks -- however, it can cause a lot of network noise and log file noise whilst debugging, and in certain cases users may in fact prefer to have less frenetic updates going on.  This should be configurable.

It may be ideal to have this configured on the GUI where the Hue Hub's IP address is set - but since there's been some question about where that IP address should really be set (perhaps a local configuration menu for each node server is more appropriate) and since this is probably something that would only change during debugging, perhaps it would be sufficient to have this value set by a local configuration/properties file that can be dynamically read by the Hue node server.

This is a low priority enhancement.

**Comment by jimboca** [comment]
I will want this as well for my Harmony hub server,  but I planned to make it a user definable parameter on the ISY  and I wanted that to change how often the poll method was called by the server manager.

**Comment by Einstein42** [comment]
Added short and long poll configurable timers per nodeserver. These are user defined when initiating the user nodeserver as such:

```
poly = PolyglotConnector()
nserver = HueNodeServer(poly, 1, 60)
```

1 is shortpoll, 60 is longpoll. 

This was tested and merged into master. Closing.

**Comment by jimboca** [comment]
It looks like this commit https://github.com/UniversalDevicesInc/Polyglot/commit/27fe6a7669b9c4c54218613df93b5d0c78bf0aab broket the configuration.  When polyglot exits, the configuration.json looks good, but then starting polyglot back up the node servers are missing.  Please fix or backout this change asap.

**Comment by Einstein42** [comment]
This is fixed.
